# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(459, 785)
        mainWindow.setMinimumSize(QSize(459, 785))
        mainWindow.setMaximumSize(QSize(459, 785))
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet(u"background-image: url(topology.png);\n"
"background-repeat: no-repeat;")
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_BR1 = QPushButton(self.centralwidget)
        self.pushButton_BR1.setObjectName(u"pushButton_BR1")
        self.pushButton_BR1.setEnabled(True)
        self.pushButton_BR1.setGeometry(QRect(180, 40, 91, 51))
        self.pushButton_BR1.setAutoFillBackground(False)
        self.pushButton_BR1.setStyleSheet(u"background: transparent;")
        self.pushButton_BR1.setCheckable(False)
        self.pushButton_BR1.setFlat(False)
        self.pushButton_ISP = QPushButton(self.centralwidget)
        self.pushButton_ISP.setObjectName(u"pushButton_ISP")
        self.pushButton_ISP.setEnabled(True)
        self.pushButton_ISP.setGeometry(QRect(180, 190, 91, 41))
        self.pushButton_ISP.setAutoFillBackground(False)
        self.pushButton_ISP.setStyleSheet(u"background: transparent;")
        self.pushButton_ISP.setCheckable(False)
        self.pushButton_ISP.setFlat(False)
        self.pushButton_HQ1 = QPushButton(self.centralwidget)
        self.pushButton_HQ1.setObjectName(u"pushButton_HQ1")
        self.pushButton_HQ1.setEnabled(True)
        self.pushButton_HQ1.setGeometry(QRect(180, 470, 81, 41))
        self.pushButton_HQ1.setAutoFillBackground(False)
        self.pushButton_HQ1.setStyleSheet(u"background: transparent;")
        self.pushButton_HQ1.setCheckable(False)
        self.pushButton_HQ1.setFlat(False)
        self.pushButton_SW1 = QPushButton(self.centralwidget)
        self.pushButton_SW1.setObjectName(u"pushButton_SW1")
        self.pushButton_SW1.setEnabled(True)
        self.pushButton_SW1.setGeometry(QRect(180, 600, 81, 41))
        self.pushButton_SW1.setAutoFillBackground(False)
        self.pushButton_SW1.setStyleSheet(u"background: transparent;")
        self.pushButton_SW1.setCheckable(False)
        self.pushButton_SW1.setFlat(False)
        self.pushButton_SW2 = QPushButton(self.centralwidget)
        self.pushButton_SW2.setObjectName(u"pushButton_SW2")
        self.pushButton_SW2.setEnabled(True)
        self.pushButton_SW2.setGeometry(QRect(50, 730, 101, 41))
        self.pushButton_SW2.setAutoFillBackground(False)
        self.pushButton_SW2.setStyleSheet(u"background: transparent;")
        self.pushButton_SW2.setCheckable(False)
        self.pushButton_SW2.setFlat(False)
        self.pushButton_SW3 = QPushButton(self.centralwidget)
        self.pushButton_SW3.setObjectName(u"pushButton_SW3")
        self.pushButton_SW3.setEnabled(True)
        self.pushButton_SW3.setGeometry(QRect(280, 720, 91, 41))
        self.pushButton_SW3.setAutoFillBackground(False)
        self.pushButton_SW3.setStyleSheet(u"background: transparent;")
        self.pushButton_SW3.setCheckable(False)
        self.pushButton_SW3.setFlat(False)
        self.pushButton_SRV1 = QPushButton(self.centralwidget)
        self.pushButton_SRV1.setObjectName(u"pushButton_SRV1")
        self.pushButton_SRV1.setEnabled(True)
        self.pushButton_SRV1.setGeometry(QRect(300, 510, 71, 91))
        self.pushButton_SRV1.setAutoFillBackground(False)
        self.pushButton_SRV1.setStyleSheet(u"background: transparent;")
        self.pushButton_SRV1.setCheckable(False)
        self.pushButton_SRV1.setFlat(False)
        self.pushButton_FW1 = QPushButton(self.centralwidget)
        self.pushButton_FW1.setObjectName(u"pushButton_FW1")
        self.pushButton_FW1.setEnabled(True)
        self.pushButton_FW1.setGeometry(QRect(190, 320, 61, 71))
        self.pushButton_FW1.setAutoFillBackground(False)
        self.pushButton_FW1.setStyleSheet(u"background: transparent;")
        self.pushButton_FW1.setCheckable(False)
        self.pushButton_FW1.setFlat(False)
        self.pushButton_PC2 = QPushButton(self.centralwidget)
        self.pushButton_PC2.setObjectName(u"pushButton_PC2")
        self.pushButton_PC2.setEnabled(True)
        self.pushButton_PC2.setGeometry(QRect(30, 40, 51, 51))
        self.pushButton_PC2.setAutoFillBackground(False)
        self.pushButton_PC2.setStyleSheet(u"background: transparent;")
        self.pushButton_PC2.setCheckable(False)
        self.pushButton_PC2.setFlat(False)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)

        self.pushButton_BR1.setDefault(False)
        self.pushButton_ISP.setDefault(False)
        self.pushButton_HQ1.setDefault(False)
        self.pushButton_SW1.setDefault(False)
        self.pushButton_SW2.setDefault(False)
        self.pushButton_SW3.setDefault(False)
        self.pushButton_SRV1.setDefault(False)
        self.pushButton_FW1.setDefault(False)
        self.pushButton_PC2.setDefault(False)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"MainWindow", None))
        self.pushButton_BR1.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_BR1.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_ISP.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_ISP.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_HQ1.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_HQ1.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_SW1.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_SW1.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_SW2.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_SW2.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_SW3.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_SW3.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_SRV1.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_SRV1.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_FW1.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_FW1.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.pushButton_PC2.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_PC2.setShortcut("")
#endif // QT_CONFIG(shortcut)
    # retranslateUi

